/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libwave_desktop_service_AudioPlayer */

#ifndef _Included_com_libwave_desktop_service_AudioPlayer
#define _Included_com_libwave_desktop_service_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_init
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_shutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_resume
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    stopFadeOut
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_stopFadeOut
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    loadMusic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_libwave_desktop_service_AudioPlayer_loadMusic
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    closeMusic
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_closeMusic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    playMusic
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_playMusic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    playMusicFadeIn
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_libwave_desktop_service_AudioPlayer_playMusicFadeIn
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libwave_desktop_service_AudioPlayer_isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     com_libwave_desktop_service_AudioPlayer
 * Method:    isPaused
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libwave_desktop_service_AudioPlayer_isPaused
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
